### ISSUE TITLE
리액트 라우터 구성하기

### ISSUE THREAD

**Issue by cottonpup** [letty-project/letty-client#4]
# 이슈 설명
프로젝트 내에서 다음과 같은 라우팅이 필요합니다.
- [x] 메인 아이콘 클릭 시, 홈화면으로 이동
- [x] 로그인 버튼 클릭 시, 로그인 화면으로 이동
- [x] 회원가입 클릭 시, 회원가입 화면으로 이동

# TODO
- [x] react-router-dom 라이브러리 설치 및 설정
- [x] App.js에 라우터 구성 추가
- [x] 각 경로(route)에 대한 컴포넌트 생성 및 연결
  - [x] 초기 화면: / -> Layout 컴포넌트
  - [x] 홈화면: / -> Home 페이지
  - [x] 로그인 화면: /login -> Login 페이지
  - [x] 회원가입 화면: /signup -> Signup 페이지(추후 구현 예정)
- [x] 리팩토링
  - [x]  BrowserRouter/Routes/Route를 이용하여 App.tsx 리팩토링
  - [x] Layout 컴포넌트 추가 후 내부에 Header 컴포넌트, Outlet 추가
  ->각 페이지마다 Header 컴포넌트를 추가하지 않아도 Header가 모든 페이지에서 보인다
