### ISSUE TITLE
2023년 10월 18일 미팅 저녁

### ISSUE THREAD

**Issue by cottonpup** [letty-project/letty-client#5]
# TODO
- [ ] Redux 가 뭔지 공부해오기
- [x] TailwindCss 공부해오기
- [x] DaisyUI 공부해오기
- [ ] CRA vs Vite 이유 정확하게 알아오기 
- [ ] SWC 란 무엇인가? 어쩔 떄 사용하고, 어쩔 때 사용을 하지 않는가? 
⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️
- [x] 부담 갖지 않기!!!!!! 나는 개짱이다 항상 외치기...
- [x] 쮝나물 => Home 화면 구현
- [x] 람쥐 => Login 화면 구현

**Comment by biyamn** [comment]
#### 직
# TODO
- [ ] Redux 가 뭔지 공부해오기
  - [ ] <a href='https://reactrouter.com/en/main/start/tutorial'>공식문서 튜토리얼</a>로 공부 중
- [ ] TailwindCss 공부해오기
- [ ] DaisyUI 공부해오기
- [ ] CRA vs Vite 이유 정확하게 알아오기 
- [ ] SWC 란 무엇인가? 어쩔 떄 사용하고, 어쩔 때 사용을 하지 않는가? 
⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️
- [ ] 부담 갖지 않기!!!!!! 나는 개짱이다 항상 외치기...
- [ ] 쮝나물 => Home 화면 구현
