### ISSUE TITLE
2023년 10월 26일 목요일 미팅

### ISSUE THREAD

**Issue by cottonpup** [letty-project/letty-client#9]
# TODO
- [ ] 다크모드에서 색상 변경하기 (아직은 다크모드 라이트모드 같게 해놓기!)
- [ ] 머지해놓은 Dev 브랜치 코드리뷰하고 수정했으면 하는 부분 코멘트달기

# Study
- [ ] Redux 튜토리얼 학습하기
  - https://redux.js.org/tutorials/index
- [ ] React Router 공부해오기 -> `람쥐`
- [ ] CRA vs Vite 이유 정확하게 알아오기
- [ ] SWC 란 무엇인가? 어쩔 때 사용하고, 어쩔 때 사용을 하지 않는가?
